// Section data for Calciatori Panini 2025-2026 — 784 figurine, 37 sezioni
// All section names are taken verbatim from the printed album.

function nums(start, end){ const a=[]; for(let i=start;i<=end;i++) a.push(String(i)); return a; }
function pfx(p, start, end){ const a=[]; for(let i=start;i<=end;i++) a.push(p+i); return a; }

window.SECTIONS = [
  // ── APERTURA ──────────────────────────────────────────────
  { id:'trofei',      name:'Trofei',                     short:'Trofei',           group:'Apertura', kind:'opening-trofei', codes:nums(1,3),    c1:'#f5b800', c2:'#7a5a00' },
  { id:'squadre-a',   name:'Le squadre della Serie A',   short:'Squadre Serie A',  group:'Apertura', kind:'team-photos',    codes:nums(4,23),   c1:'#0a3a8b', c2:'#fcc500' },
  { id:'nuove-firme', name:'Nuove firme in città',       short:'Nuove firme',      group:'Apertura', kind:'transfer',       codes:nums(24,43),  c1:'#7a5ae0', c2:'#0ea5e9' },

  // ── SQUADRE SERIE A (con Style on Pitch nella sua posizione editoriale) ──
  { id:'atalanta',    name:'Atalanta',     group:'Squadre Serie A', kind:'team', codes:nums(44,65),   c1:'#0a4a8b', c2:'#1a1a1a', city:'Bergamo' },
  { id:'bologna',     name:'Bologna',      group:'Squadre Serie A', kind:'team', codes:nums(66,87),   c1:'#a01d2e', c2:'#1a4a8b', city:'Bologna' },
  { id:'cagliari',    name:'Cagliari',     group:'Squadre Serie A', kind:'team', codes:nums(88,109),  c1:'#a01d2e', c2:'#1a4a8b', city:'Cagliari' },
  { id:'como',        name:'Como',         group:'Squadre Serie A', kind:'team', codes:nums(110,131), c1:'#1a4a8b', c2:'#0ea5e9', city:'Como' },
  { id:'cremonese',   name:'Cremonese',    group:'Squadre Serie A', kind:'team', codes:nums(132,153), c1:'#a01d2e', c2:'#6a6a6a', city:'Cremona' },
  { id:'fiorentina',  name:'Fiorentina',   group:'Squadre Serie A', kind:'team', codes:nums(154,175), c1:'#7a5ae0', c2:'#4a2a8b', city:'Firenze' },
  { id:'genoa',       name:'Genoa',        group:'Squadre Serie A', kind:'team', codes:nums(176,197), c1:'#a01d2e', c2:'#0a3a8b', city:'Genova' },
  { id:'verona',      name:'Hellas Verona',short:'Hellas Verona', group:'Squadre Serie A', kind:'team', codes:nums(198,219), c1:'#fcc500', c2:'#0a3a8b', city:'Verona' },
  { id:'inter',       name:'Inter',        group:'Squadre Serie A', kind:'team', codes:nums(220,241), c1:'#0a3a8b', c2:'#1a1a1a', city:'Milano' },
  { id:'juventus',    name:'Juventus',     group:'Squadre Serie A', kind:'team', codes:nums(242,263), c1:'#1a1a1a', c2:'#f4f4f4', city:'Torino' },
  { id:'lazio',       name:'Lazio',        group:'Squadre Serie A', kind:'team', codes:nums(264,285), c1:'#8ec5ed', c2:'#0a3a8b', city:'Roma' },
  { id:'lecce',       name:'Lecce',        group:'Squadre Serie A', kind:'team', codes:nums(286,307), c1:'#fcc500', c2:'#a01d2e', city:'Lecce' },
  { id:'milan',       name:'Milan',        group:'Squadre Serie A', kind:'team', codes:nums(308,329), c1:'#a01d2e', c2:'#1a1a1a', city:'Milano' },
  { id:'napoli',      name:'Napoli',       group:'Squadre Serie A', kind:'team', codes:nums(330,351), c1:'#0ea5e9', c2:'#0a4a8b', city:'Napoli' },
  { id:'parma',       name:'Parma',        group:'Squadre Serie A', kind:'team', codes:nums(352,373), c1:'#fcc500', c2:'#0a3a8b', city:'Parma' },
  { id:'pisa',        name:'Pisa',         group:'Squadre Serie A', kind:'team', codes:nums(374,395), c1:'#0a4a8b', c2:'#1a1a1a', city:'Pisa' },
  { id:'roma',        name:'Roma',         group:'Squadre Serie A', kind:'team', codes:nums(396,417), c1:'#a01d2e', c2:'#fcc500', city:'Roma' },
  { id:'style',       name:'Style on Pitch', group:'Squadre Serie A', kind:'style', codes:pfx('STY',1,20), c1:'#ff3df5', c2:'#7a1a8b' },
  { id:'sassuolo',    name:'Sassuolo',     group:'Squadre Serie A', kind:'team', codes:nums(418,439), c1:'#0a5a3a', c2:'#1a1a1a', city:'Sassuolo' },
  { id:'torino',      name:'Torino',       group:'Squadre Serie A', kind:'team', codes:nums(440,461), c1:'#7a1212', c2:'#4a0a0a', city:'Torino' },
  { id:'udinese',     name:'Udinese',      group:'Squadre Serie A', kind:'team', codes:nums(462,483), c1:'#1a1a1a', c2:'#f4f4f4', city:'Udine' },

  // ── CALCIATORI IA ──────────────────────────────────────────
  { id:'gem-squad',     name:'Gem Squad',        group:'Calciatori IA', kind:'ai',      codes:nums(484,495), c1:'#c8ff3d', c2:'#1a4d2a', ia:true },
  { id:'turbofreccia',  name:'Turbofreccia',     group:'Calciatori IA', kind:'ai',      codes:nums(496,505), c1:'#0ea5e9', c2:'#0a3a8b', ia:true },
  { id:'color-up',      name:'Color Up',         group:'Calciatori IA', kind:'ai',      codes:nums(506,512), c1:'#ff3df5', c2:'#7a5ae0', ia:true },
  { id:'super-glovez',  name:'Super Glovez',     group:'Calciatori IA', kind:'ai',      codes:nums(513,520), c1:'#7a5ae0', c2:'#0a3a8b', ia:true },
  { id:'trick-maestro', name:'Trick Maestro',    group:'Calciatori IA', kind:'ai',      codes:nums(521,529), c1:'#fcc500', c2:'#a05a1a', ia:true },
  { id:'boom-impatto',  name:"Boom d'Impatto",   group:'Calciatori IA', kind:'ai',      codes:nums(530,539), c1:'#ff5b2e', c2:'#a01d2e', ia:true },
  { id:'power-bros',    name:'Power Bros',       group:'Calciatori IA', kind:'ai',      codes:nums(540,541), c1:'#c8ff3d', c2:'#1a4d2a', ia:true },
  { id:'upgrade',       name:'Calciatori Upgrade', short:'Upgrade', group:'Calciatori IA', kind:'upgrade', codes:pfx('UPG',1,80), c1:'#14110d', c2:'#1a1a2a' },
  { id:'family-legacy', name:'Family Legacy',    group:'Calciatori IA', kind:'ai',      codes:nums(542,543), c1:'#ff3df5', c2:'#7a1a8b', ia:true },

  // ── ALTRE SERIE ────────────────────────────────────────────
  { id:'serie-b', name:'Serie B', group:'Altre Serie', kind:'other-league', codes:nums(544,573), c1:'#1f8a5b', c2:'#0a3a2a' },
  { id:'serie-c', name:'Serie C', group:'Altre Serie', kind:'other-league', codes:nums(574,618), c1:'#7a5ae0', c2:'#3a1a8b' },

  // ── BONUS ──────────────────────────────────────────────────
  { id:'kinder',      name:'Kinder',                  short:'Kinder',       group:'Bonus', kind:'kinder',      codes:pfx('K',1,6),    c1:'#ff7a3d', c2:'#fcc500' },
  { id:'celebration', name:'Calciatori Celebration',  short:'Celebration',  group:'Bonus', kind:'celebration', codes:pfx('CEL',1,60), c1:'#ff3df5', c2:'#fcc500' },
];

// Group order (preserves album reading order)
window.GROUPS = ['Apertura', 'Squadre Serie A', 'Calciatori IA', 'Altre Serie', 'Bonus'];

window.STICKER_STATES = {};
window.STICKER_COUNTS = {};
window.STICKER_NAMES  = {
  "1":"Serie A Trophy","2":"Coppa Italia Trophy","3":"Player of the Month Trophy",
  "4":"Atalanta","5":"Bologna","6":"Cagliari","7":"Como","8":"Cremonese","9":"Fiorentina","10":"Genoa","11":"Hellas Verona","12":"Inter","13":"Juventus","14":"Lazio","15":"Lecce","16":"Milan","17":"Napoli","18":"Parma","19":"Pisa","20":"Roma","21":"Sassuolo","22":"Torino","23":"Udinese",
  "24":"Nikola Krstovic","25":"Ciro Immobile","26":"Andrea Belotti","27":"Alvaro Morata","28":"Jamie Vardy","29":"Álvaro Morata","30":"Lorenzo Colombo","31":"Gift Orban","32":"Manuel Akanji","33":"Jonathan David","34":"Matteo Cancellieri","35":"Francesco Camarda","36":"Luka Modric","37":"Kevin De Bruyne","38":"Patrick Cutrone","39":"Michel Aebischer","40":"Evan Ferguson","41":"Nemanja Matic","42":"Giovanni Simeone","43":"Nicolo' Zaniolo",
  "44":"Scudetto Atalanta","45":"Marco Carnesecchi","46":"Marco Sportiello","47":"Giorgio Scalvini","48":"Berat Djimsiti","49":"Isak Hien","50":"Raoul Bellanova","51":"Odilon Kossounou","52":"Sead Kolasinac","53":"Ederson","54":"Marten de Roon","55":"Nicola Zalewski","56":"Davide Zappacosta","57":"Lazar Samardzic","58":"Mario Pasalic","59":"Charles de Ketelaere","60":"Ademola Lookman","61":"Kamaldeen Sulemana","62":"Nikola Krstovic","63":"Daniel Maldini","64":"Gianluca Scamacca","65":"Ivan Juric",
  "66":"Scudetto Bologna","67":"Lukasz Skorupski","68":"Federico Ravaglia","69":"Jhon Lucumi","70":"Martin Vitik","71":"Juan Miranda","72":"Emil Holm","73":"Lorenzo De Silvestri","74":"Nadir Zortea","75":"Remo Freuler","76":"Tommaso Pobega","77":"Lewis Ferguson","78":"Giovanni Fabbian","79":"Federico Bernardeschi","80":"Jens Odgaard","81":"Jonathan Rowe","82":"Riccardo Orsolini","83":"Nicolo' Cambiaghi","84":"Santiago Castro","85":"Thijs Dallinga","86":"Ciro Immobile","87":"Vincenzo Italiano",
  "88":"Scudetto Cagliari","89":"Elia Caprile","90":"Boris Radunovic","91":"Yerry Mina","92":"Sebastiano Luperto","93":"Gabriele Zappa","94":"Adam Obert","95":"Ze' Pedro","96":"Marco Palestra","97":"Michel Adopo","98":"Michael Folorunsho","99":"Gianluca Gaetano","100":"Matteo Prati","101":"Alessandro Deiola","102":"Gennaro Borrelli","103":"Mattia Felici","104":"Sebastiano Esposito","105":"Semih Kilicsoy","106":"Zito Luvumbo","107":"Leonardo Pavoletti","108":"Andrea Belotti","109":"Fabio Pisacane",
  "110":"Scudetto Como","111":"Jean Butez","112":"Nikola Cavlina","113":"Alex Valle","114":"Diego Carlos","115":"Ignace van der Brempt","116":"Jacobo Ramon","117":"Marc Oliver Kempf","118":"Mergim Vojvoda","119":"Stefan Posch","120":"Lucas da Cunha","121":"Martin Baturina","122":"Maxence Caqueret","123":"Maximo Perrone","124":"Nico Paz","125":"Sergi Roberto","126":"Nicolas Kuhn","127":"Assane Diao","128":"Anastasios Douvikas","129":"Alvaro Morata","130":"Jesus Rodriguez","131":"Cesc Fabregas",
  "132":"Scudetto Cremonese","133":"Emil Audero","134":"Marco Silvestri","135":"Filippo Terracciano","136":"Federico Baschirotto","137":"Tommaso Barbieri","138":"Floriani Mussolini","139":"Matteo Bianchetti","140":"Giuseppe Pezzella","141":"Alberto Grassi","142":"Warren Bondo","143":"Jeremy Sarmiento","144":"Alessio Zerbin","145":"Michele Collocolo","146":"Martin Payero","147":"Jari Vandeputte","148":"Federico Bonazzoli","149":"Antonio Sanabria","150":"Jamie Vardy","151":"Faris Moumbagna","152":"Franco Vazquez","153":"Davide Nicola",
  "154":"Scudetto Fiorentina","155":"David de Gea","156":"Tommaso Martinelli","157":"Luca Ranieri","158":"Pablo Mari'","159":"Tariq Lamptey","160":"Pietro Comuzzo","161":"Dodo'","162":"Fabiano Parisi","163":"Marin Pongracic","164":"Mattia Viti","165":"Robin Gosens","166":"Jacopo Fazzini","167":"Rolando Mandragora","168":"Simon Sohm","169":"Nicolussi Caviglia","170":"Nicolo' Fagioli","171":"Edin Dzeko","172":"Moise Kean","173":"Roberto Piccoli","174":"Albert Gudmundsson","175":"Stefano Pioli",
  "176":"Scudetto Genoa","177":"Nicola Leali","178":"Benjamin Siegrist","179":"Johan Vasquez","180":"Alessandro Marcandalli","181":"Leo Ostigard","182":"Aaron Martin","183":"Brooke Norton-Cuffy","184":"Stefano Sabelli","185":"Sebastian Otoa","186":"Patrizio Masini","187":"Ruslan Malinovskyi","188":"Albert Grønbæk","189":"Morten Frendrup","190":"Junior Messias","191":"Nicolae Stanciu","192":"Mikael Egill Ellertsson","193":"Morten Thorsby","194":"Valentin Carboni","195":"Lorenzo Colombo","196":"Vitinha","197":"Patrick Vieira",
  "198":"Scudetto Hellas Verona","199":"Lorenzo Montipo'","200":"Simone Perilli","201":"Unai Nunez","202":"Enzo Ebosse","203":"Domagoj Bradaric","204":"Bella-Kotchap","205":"Rafik Belghali","206":"Victor Nelsson","207":"Nicolas Valentini","208":"Martin Frese","209":"Suat Serdar","210":"Al-Musrati","211":"Abdou Harroui","212":"Roberto Gagliardini","213":"Antoine Bernede","214":"Akpa Akpro","215":"Amin Sarr","216":"Daniel Mosquera","217":"Gift Orban","218":"Giovane","219":"Paolo Zanetti",
  "220":"Scudetto Inter","221":"Yann Sommer","222":"Josep Martinez","223":"Stefan De Vrij","224":"Francesco Acerbi","225":"Manuel Akanji","226":"Alessandro Bastoni","227":"Yann-Aurel Bisseck","228":"Federico Dimarco","229":"Carlos Augusto","230":"Denzel Dumfries","231":"Davide Frattesi","232":"Petar Sucic","233":"Piotr Zielinski","234":"Hakan Calhanoglu","235":"Nicolo' Barella","236":"Henrikh Mkhitaryan","237":"Francesco Pio Esposito","238":"Lautaro Martinez","239":"Marcus Thuram","240":"Ange-Yoan Bonny","241":"Cristian Chivu",
  "242":"Scudetto Juventus","243":"Michele Di Gregorio","244":"Mattia Perin","245":"Andrea Cambiaso","246":"Federico Gatti","247":"Bremer","248":"Juan Cabal","249":"Pierre Kalulu","250":"Lloyd Kelly","251":"Joao Mario","252":"Teun Koopmeiners","253":"Weston McKennie","254":"Fabio Miretti","255":"Manuel Locatelli","256":"Khephren Thuram","257":"Lois Openda","258":"Francisco Conceicao","259":"Dusan Vlahovic","260":"Kenan Yildiz","261":"Jonathan David","262":"Edon Zhegrova","263":"Igor Tudor",
  "264":"Scudetto Lazio","265":"Ivan Provedel","266":"Christos Mandas","267":"Alessio Romagnoli","268":"Luca Pellegrini","269":"Adam Marusic","270":"Mario Gila","271":"Nuno Tavares","272":"Oliver Provstgaard","273":"Fisayo Dele-Bashiru","274":"Nicolo' Rovella","275":"Mattia Zaccagni","276":"Matias Vecino","277":"Matteo Guendouzi","278":"Reda Belahyane","279":"Danilo Cataldi","280":"Gustav Isaksen","281":"Valentin Castellanos","282":"Matteo Cancellieri","283":"Boulaye Dia","284":"Pedro","285":"Maurizio Sarri",
  "286":"Scudetto Lecce","287":"Wladimiro Falcone","288":"Christian Fruchtl","289":"Tiago Gabriel","290":"Christ-Owen Kouassi","291":"Antonino Gallo","292":"Danilo Veiga","293":"Kialonda Gaspar","294":"Jamil Siebert","295":"Corrie Ndaba","296":"Medon Berisha","297":"Balthazar Pierret","298":"Mohamed Drame'","299":"Lassana Coulibaly","300":"Ylber Ramadani","301":"Francesco Camarda","302":"Riccardo Sottil","303":"Tete Morente","304":"Nikola Stulic","305":"Santiago Pierotti","306":"Lameck Banda","307":"Eusebio Di Francesco",
  "308":"Scudetto Milan","309":"Mike Maignan","310":"Pietro Terracciano","311":"Koni de Winter","312":"David Odogu","313":"Fikayo Tomori","314":"Pervis Estupinan","315":"Strahinja Pavlovic","316":"Zachary Athekame","317":"Matteo Gabbia","318":"Adrien Rabiot","319":"Alexis Saelemaekers","320":"Ardon Jashari","321":"Youssouf Fofana","322":"Luka Modric","323":"Ruben Loftus-Cheek","324":"Samuele Ricci","325":"Christian Pulisic","326":"Christopher Nkunku","327":"Rafael Leao","328":"Santiago Gimenez","329":"Massimiliano Allegri",
  "330":"Scudetto Napoli","331":"Alex Meret","332":"Vanja Milinkovic-Savic","333":"Alessandro Buongiorno","334":"Giovanni Di Lorenzo","335":"Leonardo Spinazzola","336":"Mathias Olivera","337":"Sam Beukema","338":"Amir Rrahmani","339":"Eljif Elmas","340":"Billy Gilmour","341":"Stanislav Lobotka","342":"Andre'-Frank Anguissa","343":"Kevin De Bruyne","344":"Scott McTominay","345":"Lorenzo Lucca","346":"Romelu Lukaku","347":"Noa Lang","348":"Rasmus Hojlund","349":"David Neres","350":"Matteo Politano","351":"Antonio Conte",
  "352":"Scudetto Parma","353":"Zion Suzuki","354":"Edoardo Corvi","355":"Abdoulaye Ndiaye","356":"Emanuele Valeri","357":"Mathias Lovik","358":"Enrico Delprato","359":"Alessandro Circati","360":"Mariano Troilo","361":"Lautaro Valenti","362":"Christian Ordonez","363":"Adrian Bernabe'","364":"Nahuel Estevez","365":"Mandela Keita","366":"Oliver Sorensen","367":"Gaetano Oristanio","368":"Pontus Almqvist","369":"Jacob Ondrejka","370":"Patrick Cutrone","371":"Milan Djuric","372":"Mateo Pellegrino","373":"Carlos Cuesta",
  "374":"Scudetto Pisa","375":"Simone Scuffet","376":"Adrian Semper","377":"Mateus Lusuardi","378":"Samuele Angori","379":"Raul Albiol","380":"Antonio Caracciolo","381":"Simone Canestrelli","382":"Arturo Calabresi","383":"Michel Aebischer","384":"Lorran","385":"Isak Vural","386":"Idrissa Toure'","387":"Matteo Tramoni","388":"Juan Cuadrado","389":"Marius Marin","390":"Stefano Moreo","391":"Mehdi Leris","392":"M'Bala Nzola","393":"Henrik Meister","394":"Calvin Stengs","395":"Alberto Gilardino",
  "396":"Scudetto Roma","397":"Mile Svilar","398":"Pierluigi Gollini","399":"Kostas Tsimikas","400":"Gianluca Mancini","401":"Angelino","402":"Zeki Celik","403":"Mario Hermoso","404":"Evan Ndicka","405":"Wesley","406":"Lorenzo Pellegrini","407":"Lorenzo Pellegrini","408":"Niccolo' Pisilli","409":"Neil El Aynaoui","410":"Manu Kone","411":"Leon Bailey","412":"Stephan El Shaarawy","413":"Paulo Dybala","414":"Artem Dovbyk","415":"Evan Ferguson","416":"Matias Soule'","417":"Gian Piero Gasperini",
  "418":"Scudetto Sassuolo","419":"Stefano Turati","420":"Arijanet Muric","421":"Filippo Romagna","422":"Sebastian Walukiewicz","423":"Woyo Coulibaly","424":"Tarik Muharemovic","425":"Josh Doig","426":"Jay Idzes","427":"Daniel Boloca","428":"Luca Lipani","429":"Kristian Thorstvedt","430":"Aster Vranckx","431":"Nemanja Matic","432":"Ismael Kone'","433":"Alieu Fadera","434":"Andrea Pinamonti","435":"Cristian Volpato","436":"Domenico Berardi","437":"Walid Cheddira","438":"Armand Laurentie'","439":"Fabio Grosso",
  "440":"Scudetto Torino","441":"Franco Israel","442":"Alberto Paleari","443":"Valentino Lazaro","444":"Cristiano Biraghi","445":"Guillermo Maripan","446":"Marcus Pedersen","447":"Adam Masina","448":"Saul Coco","449":"Ardian Ismajli","450":"Kristjan Asllani","451":"Cesare Casadei","452":"Ivan Ilic","453":"Tino Anjorin","454":"Gvidas Gineitis","455":"Nikola Vlasic","456":"Ché Adams","457":"Zakaria Aboukhlal","458":"Giovanni Simeone","459":"Cyril Ngonge","460":"Duvan Zapata","461":"Marco Baroni",
  "462":"Scudetto Udinese","463":"Razvan Sava","464":"Maduka Okoye","465":"Saba Goglichidze","466":"Nicolo' Bertola","467":"Thomas Kristensen","468":"Oumar Solet","469":"Hassane Kamara","470":"Alessandro Zanoli","471":"Kingsley Ehizibue","472":"Jordan Zemura","473":"Jesper Karlström","474":"Sandi Lovric","475":"Jakub Piotrowski","476":"Lennon Miller","477":"Jurgen Ekkelenkamp","478":"Arthur Atta","479":"Nicolo' Zaniolo","480":"Adam Buksa","481":"Iker Bravo","482":"Keinan Davis","483":"Kosta Runjaic",
  "484":"Charles De Ketelaere","485":"Riccardo Orsolini","486":"Nico Paz","487":"Moise Kean","488":"Lautaro Martinez","489":"Kenan Yildiz","490":"Mattia Zaccagni","491":"Christian Pulisic","492":"Romelu Lukaku","493":"Adrian Bernabe'","494":"Paulo Dybala","495":"Domenico Berardi",
  "496":"Raoul Bellanova","497":"Assane Diao","498":"Federico Dimarco","499":"Giovane","500":"Joao Mario","501":"Nuno Tavares","502":"Rafael Leao","503":"Noa Lang","504":"Juan Cuadrado","505":"Armand Laurentie'",
  "506":"Santiago Castro","507":"Jesus Rodriguez","508":"Pietro Comuzzo","509":"Valentin Carboni","510":"Francesco Camarda","511":"Cesare Casadei","512":"Arthur Atta",
  "513":"Elia Caprile","514":"David De Gea","515":"Lorenzo Montipo'","516":"Nicola Leali","517":"Wladimiro Falcone","518":"Mike Maignan","519":"Zion Suzuki","520":"Mile Svilar",
  "521":"Federico Bernardeschi","522":"Federico Bonazzoli","523":"Nicolae Stanciu","524":"Nicolo' Barella","525":"Valentin Castellanos","526":"Luka Modric","527":"Scott McTominay","528":"Matias Soule'","529":"Nikola Vlasic",
  "530":"Giorgio Scalvini","531":"Yerry Mina","532":"Federico Baschirotto","533":"Alessandro Bastoni","534":"Bremer","535":"Kialonda Gaspar","536":"Andre'-Frank Anguissa","537":"Idrissa Toure'","538":"Manu Kone'","539":"Oumar Solet",
  "540":"Pio Esposito / Sebastiano Esposito","541":"Marcus Thuram / Khephren Thuram",
  "542":"Daniel Maldini / Paolo Maldini","543":"Louis Buffon / Gianluigi Buffon",
  "544":"Avellino / Bari","545":"Avellino","546":"Bari","547":"Carrarese / Catanzaro","548":"Carrarese","549":"Catanzaro","550":"Cesena / Empoli","551":"Cesena","552":"Empoli","553":"Frosinone / Juve Stabia","554":"Frosinone","555":"Juve Stabia","556":"Mantova / Modena","557":"Mantova","558":"Modena","559":"Monza / Padova","560":"Monza","561":"Padova","562":"Palermo / Pescara","563":"Palermo","564":"Pescara","565":"Reggiana / Sampdoria","566":"Reggiana","567":"Sampdoria","568":"Spezia / Sudtirol","569":"Spezia","570":"Sudtirol","571":"Venezia / Virtus Entella","572":"Venezia","573":"Virtus Entella",
  "574":"Albinoleffe / Alcione Milano / Arzignano / Cittadella","575":"Albinoleffe / Alcione Milano","576":"Arzignano / Cittadella","577":"Dolomiti / Giana Erminio / Inter U23 / Vicenza","578":"Dolomiti / Giana Erminio","579":"Inter U23 / Vicenza","580":"Lecco / Lumezzane / Novara / Ospitaletto","581":"Lecco / Lumezzane","582":"Novara / Ospitaletto","583":"Pergolettese / Pro Patria / Pro Vercelli / Renate","584":"Pergolettese / Pro Patria","585":"Pro Vercelli / Renate","586":"Trento / Triestina / Union Brescia / Virtus Verona","587":"Trento / Triestina","588":"Union Brescia / Virtus Verona","589":"Arezzo / Ascoli / Bra / Campobasso","590":"Arezzo / Ascoli","591":"Bra / Campobasso","592":"Carpi / Forli / Gubbio / Guidonia Montecelio","593":"Carpi / Forli","594":"Gubbio / Guidonia Montecelio","595":"Juventus / Livorno / Perugia / Pianese","596":"Juventus / Livorno","597":"Perugia / Pianese","598":"Pineto / Pontedera / Ravenna / Rimini","599":"Pineto / Pontedera","600":"Ravenna / Rimini","601":"Sambenedettese / Ternana / Torres / Vis Pesaro","602":"Sambenedettese / Ternana","603":"Torres / Vis Pesaro","604":"Atalanta U23 / Cerignola / Picerno / Benevento","605":"Atalanta U23 / Cerignola","606":"Picerno / Benevento","607":"Casarano / Casertana / Catania / Cavese","608":"Casarano / Casertana","609":"Catania / Cavese","610":"Cosenza / Crotone / Foggia / Giugliano","611":"Cosenza / Crotone","612":"Foggia / Giugliano","613":"Latina / Monopoli / Potenza / Salernitana","614":"Latina / Monopoli","615":"Potenza / Salernitana","616":"Siracusa / Sorrento / Altamura / Trapani","617":"Siracusa / Sorrento","618":"Altamura / Trapani",
  "STY1":"Atalanta","STY2":"Bologna","STY3":"Cagliari","STY4":"Como","STY5":"Cremonese","STY6":"Fiorentina","STY7":"Genoa","STY8":"Hellas Verona","STY9":"Inter","STY10":"Juventus","STY11":"Lazio","STY12":"Lecce","STY13":"Milan","STY14":"Napoli","STY15":"Parma","STY16":"Pisa","STY17":"Roma","STY18":"Sassuolo","STY19":"Torino","STY20":"Udinese",
  "K1":"Logo SuperCup EA Sports FC","K2":"Copa SuperCup","K3":"Logo Napoli","K4":"Logo Inter","K5":"Logo Bologna","K6":"Logo Milan",
  "UPG1":"Lorenzo Bernasconi","UPG2":"Honest Ahanor","UPG3":"Giacomo Raspadori","UPG4":"Raffaele Palladino","UPG5":"Torbjørn Heggem","UPG6":"Eivind Helland","UPG7":"João Mário","UPG8":"Simon Sohm","UPG9":"Alberto Dossena","UPG10":"Othniël Raterink","UPG11":"Ibrahim Sulemana","UPG12":"Agustín Albarracín","UPG13":"Alberto Moreno","UPG14":"Ivan Smolčić","UPG15":"Adrian Lahdo","UPG16":"Jayden Addai","UPG17":"Sebastiano Luperto","UPG18":"Youssef Maleh","UPG19":"Morten Thorsby","UPG20":"Milan Đurić","UPG21":"Giovanni Fabbian","UPG22":"Marco Brescianini","UPG23":"Manor Solomon","UPG24":"Paolo Vanoli","UPG25":"Justin Bijlow","UPG26":"Nils Zätterström","UPG27":"Tommaso Baldanzi","UPG28":"Daniele De Rossi","UPG29":"Andrias Edmundsson","UPG30":"Sandi Lovrić","UPG31":"Kieron Bowie","UPG32":"Paolo Sammarco","UPG33":"Raffaele Di Gennaro","UPG34":"Matteo Darmian","UPG35":"Luís Henrique","UPG36":"Andy Diouf","UPG37":"Emil Holm","UPG38":"Filip Kostić","UPG39":"Jérémie Boga","UPG40":"Luciano Spalletti","UPG41":"Edoardo Motta","UPG42":"Kenneth Taylor","UPG43":"Daniel Maldini","UPG44":"Petar Ratkov","UPG45":"Omri Gandelman","UPG46":"Sadik Fofana","UPG47":"Oumar Ngom","UPG48":"Walid Cheddira","UPG49":"Lorenzo Torriani","UPG50":"Davide Bartesaghi","UPG51":"Cheveyo Balentien","UPG52":"Niclas Füllkrug","UPG53":"Juan Jesus","UPG54":"Antonio Vergara","UPG55":"Alisson Santos","UPG56":"Giovane","UPG57":"Franco Carboni","UPG58":"Hans Nicolussi Caviglia","UPG59":"Gabriel Strefezza","UPG60":"Nesta Elphege","UPG61":"Felipe Loyola","UPG62":"Samuel Iling-Junior","UPG63":"Rafiu Durosinmi","UPG64":"Oscar Hiljemark","UPG65":"Bryan Zaragoza","UPG66":"Lorenzo Venturino","UPG67":"Robinio Vaz","UPG68":"Donyell Malen","UPG69":"Ulisses Garcia","UPG70":"Pedro Felipe","UPG71":"Darryl Bakola","UPG72":"M'Bala Nzola","UPG73":"Rafa Obrador","UPG74":"Matteo Prati","UPG75":"Emirhan İlkhan","UPG76":"Sandro Kulenović","UPG77":"Branimir Mlačić","UPG78":"Juan Arizala","UPG79":"Christian Kabasele","UPG80":"Oier Zarraga",
  "CEL1":"EA Sports FC SuperCup","CEL2":"EA Sports FC SuperCup","CEL3":"EA Sports FC SuperCup","CEL4":"EA Sports FC SuperCup","CEL5":"Coppa Italia Frecciarossa","CEL6":"Coppa Italia Frecciarossa","CEL7":"Coppa Italia Frecciarossa","CEL8":"Coppa Italia Frecciarossa","CEL9":"Film del Campionato","CEL10":"Film del Campionato","CEL11":"Film del Campionato","CEL12":"Film del Campionato","CEL13":"Film del Campionato","CEL14":"Film del Campionato","CEL15":"Film del Campionato","CEL16":"Film del Campionato","CEL17":"Film del Campionato","CEL18":"Film del Campionato","CEL19":"Film del Campionato","CEL20":"Film del Campionato","CEL21":"Film del Campionato","CEL22":"Film del Campionato","CEL23":"Film del Campionato","CEL24":"Film del Campionato","CEL25":"Film del Campionato","CEL26":"Film del Campionato","CEL27":"Film del Campionato","CEL28":"Film del Campionato","CEL29":"Film del Campionato","CEL30":"Film del Campionato","CEL31":"Film del Campionato","CEL32":"Film del Campionato","CEL33":"Film del Campionato","CEL34":"Film del Campionato","CEL35":"Film del Campionato","CEL36":"Film del Campionato","CEL37":"Film del Campionato","CEL38":"Film del Campionato","CEL39":"Film del Campionato","CEL40":"Film del Campionato","CEL41":"Film del Campionato","CEL42":"Film del Campionato","CEL43":"Film del Campionato","CEL44":"Film del Campionato","CEL45":"Campioni d'Italia 1/3","CEL46":"Campioni d'Italia 2/3","CEL47":"Campioni d'Italia 3/3","CEL48":"Capodanno","CEL49":"Player of the month","CEL50":"Player of the month","CEL51":"Player of the month","CEL52":"Player of the month","CEL53":"Player of the month","CEL54":"Coach of the month","CEL55":"Coach of the month","CEL56":"Coach of the month","CEL57":"Coach of the month","CEL58":"Coach of the month","CEL59":"Player of the match","CEL60":"The Coach experience"
};

// Default: tutte le figurine iniziano come "mancanti" (non possedute)
window.SECTIONS.forEach(sec => {
  sec.codes.forEach(code => {
    window.STICKER_STATES[code] = 'missing';
  });
});

// Compute initial counts
window.albumStats = function(){
  let have=0, missing=0, doubles=0, extras=0;
  for (const code in window.STICKER_STATES){
    const s = window.STICKER_STATES[code];
    if (s === 'have') have++;
    else if (s === 'missing') missing++;
    else if (s === 'double'){ have++; doubles++; extras += (window.STICKER_COUNTS[code] || 2) - 1; }
  }
  return { have, missing, doubles, total: have + missing, ownedSlots: have, totalPhysical: have + extras };
};

// ── Persistenza locale ──────────────────────────────────────
// Salva e ripristina lo stato dell'album sul dispositivo dell'utente,
// così le modifiche sopravvivono ai refresh.
const FB_STORAGE_KEY = 'figubook-calciatori-2526-v1';

window.saveAlbum = function(){ /* persistenza gestita da Firestore, vedi figubook-db.js */ };

window.resetAlbum = function(){ /* reset gestito da figubook-album-single.js via Firestore */ };
